name: CI - Unit Tests

on:
  push:
    branches:
      - hw_test
  pull_request:
    branches:
      - hw_test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      # - name: Restore dependencies
      #   run: dotnet restore ./ASP.NET/Homeworks/UnitTests/src/PromoCodeFactory.sln

      - name: Build the solution
        run: dotnet build "./ASP.NET/Homeworks/UnitTests/src/PromoCodeFactory.sln" --configuration Release --no-restore

      - name: Run unit tests
        run: |
          dotnet test "./ASP.NET/Homeworks/UnitTests/src/PromoCodeFactory.UnitTests/PromoCodeFactory.UnitTests.csproj" \
            --configuration Release \
            --no-build \
            --logger "trx;LogFileName=TestResults.trx"

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: TestResults
          path: ./ASP.NET/Homeworks/UnitTests/src/PromoCodeFactory.UnitTests/TestResults/